name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          plugin_wakatime: yes
          plugin_wakatime_sections: time, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: "graph"
          plugin_repositories: yes
          plugin_repositories_featured: CactusMessenger, ThreeBody
          plugin_languages: yes
          plugin_languages_ignored: javascript
